Async strategy #17
GolosChain/cyberway.notifier pull request #25
Opened 2019-06-27 23:41 UTC by DedbaradeD

2019-06-28 09:50 UTC, zxcat requested changes
this will not work.
in async case there will be several objects alive at certain moments (almost always), so it's not enough to have single variable to store object. it will be overwritten on next loop cycle and pointers become invalidated. you need to store objects and subjects in some container and free them in when ack callback received (and on error, but it's also possible to resend same object if error is recoverable).

For me it's preferable to add additional abstraction layer between notifier and nats api, which manages objects lifetime itself, so we can easily reuse it in future. But it's not strict requirement.

2019-06-28 09:54 UTC, zxcat commented on notifier.cpp
> +            s = stanConnection_PublishAsync(sc, subj, line->c_str(), line->size(), _publish_ack_cb, static_cast<void*>(line));
do not remove `sync` strategy completely, there should be switch (at least ifdef) to change strategy

2019-06-30 16:02 UTC, afalaleev requested changes
You should investigate the sources of nats.

For example, here the nats-library store pointer to line, which you pass to it:
https://github.com/nats-io/nats.c/blob/master/src/stan/pub.c#L285-L286

So, on the next reading from stdin, you will rewrite data, which is not currently send to the server.

Here, you will find calling of callback:
https://github.com/nats-io/nats.c/blob/master/src/stan/pub.c#L223

2019-07-02 08:50 UTC, afalaleev approved these changes

2019-07-03 10:55 UTC, merged